TaskManagementSystem/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TaskManagementSystem.Attribute;
using TaskManagementSystem.Core.Contracts;
using TaskManagementSystem.Core.Exceptions;
using TaskManagementSystem.Core.Extentions;
using TaskManagementSystem.Core.Models.Assignment;

namespace TaskManagementSystem.Controllers
{
    public class AssignmentController : BaseController
    {
        private readonly IAssignmentService assignmentService;

        private readonly IAssigneeService assigneeService;

        private readonly ILogger logger;

        public AssignmentController(
            IAssignmentService _assignmentService,
            IAssigneeService _assigneeService,
            ILogger<AssignmentController> _logger)
        {
            assignmentService = _assignmentService;
            assigneeService = _assigneeService;
            logger = _logger;
        }

    [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> All([FromQuery]AllAssignmentsQueryModel query)
        {
            var model = await assignmentService.AllAsync(
                query.Category,
                query.SearchItem,
                query.Sorting,
                query.CurrentPage,
                query.AssignmentsPerPage);

            query.TotalAssignmentsCount = model.TotalAssignmentsCount;
            query.Assignments = model.Assignments;
            query.Categories = await assignmentService.AllCategoriesNamesAsync();
            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            var userId = User.Id();
            IEnumerable<AssignmentServiceModel> model;

            if (await assigneeService.ExistsByIdAsync(userId))
            {
                int assigneeId = await assigneeService.GetAssigneeIdAsync(userId) ?? 0;

                model = await assignmentService.AllAssignmentsByAssigneeIdAsync(assigneeId);
            }
            else
            {
                model = await assignmentService.AllAssignmentsByUserId(userId);
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string information)
        {
            if (await assignmentService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            var model = await assignmentService.AssignmentDetailsByIdAsync(id);

            if (information != model.GetInformation())
            {
                return BadRequest();
            }

            return View(model);
        }

        [HttpGet]
        [MustBeAssignee]
        public async Task<IActionResult> Add()
        {
            var model = new AssignmentFormModel()
            {
                Categories = await assignmentService.AllCategoriesAsync()
            };

            return View(model);
        }

        [HttpPost]
        [MustBeAssignee]
        public async Task<IActionResult> Add(AssignmentFormModel model)
        {
            if (await assignmentService.CategoryExistsAsync(model.CategoryId) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist.");
            }

            if (ModelState.IsValid == false)
            {
                model.Categories = await assignmentService.AllCategoriesAsync();

                return View(model);
            }

            int? assigneeId = await assigneeService.GetAssigneeIdAsync(User.Id());

            int newAssigneeId = await assignmentService.CreateAsync(model, assigneeId ?? 0);

            return RedirectToAction(nameof(Details), new { id = newAssigneeId, information = model.GetInformation() });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if (!await assignmentService.ExistsAsync(id))
            {
                return BadRequest();
            }

            if (!await assignmentService.HasAssigneeWithIdAsync(id, User.Id()) &&
                !User.IsAdmin())
            {
                return Unauthorized();
            }

            var model = await assignmentService.GetAssignmentFormModelByIdAsync(id);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, AssignmentFormModel model)
        {
            if (!await assignmentService.ExistsAsync(id))
            {
                return BadRequest();
            }

            if (!await assignmentService.HasAssigneeWithIdAsync(id, User.Id()) &&
                !User.IsAdmin())
            {
                return Unauthorized();
            }

            if (!await assignmentService.CategoryExistsAsync(model.CategoryId))
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist.");
            }

            if (!ModelState.IsValid)
            {
                model.Categories = await assignmentService.AllCategoriesAsync();

                return View(model);
            }

            await assignmentService.EditAsync(id, model);

            return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (await assignmentService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await assignmentService.HasAssigneeWithIdAsync(id, User.Id()) == false &&
                !User.IsAdmin())
            {
                return Unauthorized();
            }

            var assignment = await assignmentService.AssignmentDetailsByIdAsync(id);

            var model = new AssignmentDetailsViewModel()
            {
                Id = id,
                Description = assignment.Description,
                Title = assignment.Title
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(AssignmentDetailsViewModel model)
        {
            if (!await assignmentService.ExistsAsync(model.Id))
            {
                return BadRequest();
            }

            if (!await assignmentService.HasAssigneeWithIdAsync(model.Id, User.Id()) &&
                !User.IsAdmin())
            {
                return Unauthorized();
            }

            await assignmentService.DeleteAsync(model.Id);


            return RedirectToAction(nameof(All));
        }

        [HttpPost]
        public async Task<IActionResult> Accept(int id)
        {
            if (await assignmentService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            if (await assigneeService.ExistsByIdAsync(User.Id()) &&
                !User.IsAdmin())
            {
                return Unauthorized();
            }

            if (await assignmentService.IsAcceptedAsync(id))
            {
                return BadRequest();
            }

            await assignmentService.AcceptAsync(id, User.Id());

            return RedirectToAction(nameof(Mine));
        }

        [HttpPost]
        public async Task<IActionResult> Leave(int id)
        {
            if (await assignmentService.ExistsAsync(id) == false)
            {
                return BadRequest();
            }

            try
            {
                await assignmentService.LeaveAsync(id, User.Id());
            }
            catch (UnauthorizedActionException uae)
            {
                logger.LogError(uae, "AssignmentController/Leave");

                return Unauthorized();
            }


            return RedirectToAction(nameof(Mine));
        }
    }
}

TaskManagementSystem/Views/Shared/_AssignmentFormPartial.cshtml
@model AssignmentFormModel

<style>
    .row {
        max-width: 900px;
        margin: 0 auto;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-family: "Lucida Console", "Courier New", monospace;
    }
    .form-group {
        margin-bottom: 20px;
    }
    .form-group label {
        display: block;
        margin-bottom: 5px;
        font-size:25px;
    }
    .form-group input[type="text"], .form-group textarea {
        width: 100%;
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 3px;
        box-sizing: border-box;
    }
    .form-group textarea {
        height: 100px;
    }
    .form-group button {
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }
    .form-group button:hover {
        background-color: #0056b3;
    }
</style>

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" placeholder="Title">
                <span asp-validation-for="Title" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" rows="4" class="form-control" placeholder="Describe your problem/task"></textarea>
                <span asp-validation-for="Description" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoneBy"></label>
                <input asp-for="DoneBy" class="form-control" placeholder="(mm/dd/yyyy)">
                <span asp-validation-for="DoneBy" class="small text-danger"></span>
            </div>
            <div style="width: 100%;" class="form-group">
                <label asp-for="Paid"></label>
                <input asp-for="Paid" class="form-control">
                <span asp-validation-for="Paid" class="small text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId"></label>
                <select asp-for="CategoryId" class="form-control">
                    @foreach (var category in Model.Categories)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="CategoryId" class="small text-danger"></span>
            </div>

            <div class="text-center">
                <input class="btn btn-primary mt-3" type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

TaskManagementSystem/Views/Shared/_AssignmentPartial.cshtml
@model AssignmentServiceModel
@inject IAssigneeService assigneeService
@inject IAssignmentService assignmentService

<div class="col-md-4">
    <div style="background-color:#ff8c8c" class="card mb-3">
        <div class="card-body text-center">
            <h4>@Model.Title</h4>
            <h6>Description: <b>@Model.Description</b></h6>
            <h6>
                Price Paid Upon Completion:
                <b>@String.Format("{0:f2}", Model.Paid) BGN</b>
            </h6>
            <h6>(@(Model.IsAssigned ? "Assigned" : "Not Assigned"))</h6>
            <br />
            <a asp-controller="Assignment" asp-action="Details" asp-route-id="@Model.Id" asp-route-information="@Model.GetInformation()" 
            class="btn btn-success" style="background:#3630a3;color:white;">Details</a>
            @if (this.User.Identity.IsAuthenticated)
            {
                @if (await assignmentService.HasAssigneeWithIdAsync(Model.Id, User.Id()) ||
                User.IsAdmin())
                {
                     <a asp-controller="Assignment" asp-action="Edit" asp-route-id="@Model.Id"
                    class="btn btn-warning" style="background:#f58442;color:#ffd94f;">Edit</a>
                     <a asp-controller="Assignment" asp-action="Delete" asp-route-id="@Model.Id"
                    class="btn btn-danger" style="background:#940000;color:#ff4d4d;">Delete</a>
                }
                <p></p>
                @if (!Model.IsAssigned && ((await assigneeService.ExistsByIdAsync(User.Id())) == false ||
                User.IsAdmin()))
                {
                    <form class="input-group-sm" asp-controller="Assignment"
                  asp-action="Accept" asp-route-id="@Model.Id" method="post">
                        <input style="background:#00ff11;color:#005c06;" class="btn btn-primary" type="submit" value="Accept" />
                    </form>
                }
                else if(await assignmentService.IsAcceptedByUserWithIdAsync(Model.Id, User.Id()))
                {
                    <form asp-controller="Assignment" asp-action="Leave"
                  asp-route-id="@Model.Id" method="post">
                        <input style="background:#000000;color:#ffffff;" class="btn btn-primary" type="submit" value="Leave" />
                    </form>
                }
            }
        </div>
    </div>
</div>

TaskManagementSystem/Views/Shared/_Layout.cshtml
@using TaskManagementSystem.Components
<!DOCTYPE html>
<html lang="en" 
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Work To Do</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskManagementSystem.styles.css" asp-append-version="true" />
</head>
<body style="background-color:#949494;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tasks Assigned</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @await Component.InvokeAsync(nameof(MainMenuComponent))
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="position: fixed; bottom: 0;" class="border-top footer text-muted">
        <div style="color:#000000" class="container">
            &copy; @DateTime.Today.Year - TaskManagementSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>